### ISSUE TITLE
Connect to MySQL via MySQL Workbench

### ISSUE THREAD

**Issue by unfulvio** [wckr/wocker-dockerfile#3]
I'm attempting to connect to MySQL in Wocker via MySQL Workbench.

The default port (3306?) is not working. I tried to connect both as wordpress/wordpress and root/root.

Perhaps it should be opened other than port 80?
https://github.com/wckr/wocker-dockerfile/blob/master/wheezy/Dockerfile#L65

I'm a bit new to docker, therefore I might be doing mistakes.

How would you suggest to inspect MySQL in Wocker? I think it's ok not to add PhpMyAdmin, to keep Wocker light. But MySQL tables inspection is useful especially in plugins development.

Thank you.

**Comment by ixkaito** [comment]
At the moment, you can only connect to MySQL from the container itself.

```
$ vagrant ssh
```

```
core@wocker ~ $ wocker exec -it CONTAINER bash
```

Please see `exec` on http://wckr.github.io/commands/

```
root@****:/var/www/wordpress# mysql -uwordpress -pwordpress
```

You can also use WP-CLI to operate the database.

```
root@****:/var/www/wordpress# wp --allow-root db
```

Note: `--allow-root` is required.
For more information: http://wp-cli.org/

To be able to connect to MySQL from host machine might be useful. Someone wanted to use Sequel Pro.

**Comment by unfulvio** [comment]
maybe something like a SSH tunnel like VVV does is possible?

https://github.com/Varying-Vagrant-Vagrants/VVV/wiki/Connecting-to-MySQL

I can connect via SSH using the insecure key in `~/.vagrant.d/insecure_private_key` with user `core` (default in CoreOS), but again couldn't connect to MySQL yet

**Comment by ixkaito** [comment]
I have to say you cannot connect MySQL via Workbench or Sequel Pro at the moment. I'm considering to enable the connection to MySQL from the host machine in the next version.

**Comment by ixkaito** [comment]
Now, you can connect to MySQL from outside the container in version 0.5.0, so GUI tools like Sequel Pro or Workbench are available. Please update Wocker.

#### Update Wocker

```
$ vagrant ssh
```

```
core@wocker ~ $ wocker update
```

Note: you can only connect to the container created by v0.5.0 or later.

#### Information of database

Host: `wocker.dev` (or `172.17.8.23`)
User: `wordpress`
Password: `wordpress`
Database: `wordpress`
Port: `3306`

**Comment by unfulvio** [comment]
thanks :)

ps if you plan to make wocker more a community project, perhaps you can add some discussion channel in http://wckr.github.io/

**Comment by ixkaito** [comment]
Thanks! It sounds good. I'll think about it :)
